name: geokisan_geofarmer
description: Precision agriculture bilingual super-app for farmers across Pakistan.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  image_picker: ^1.0.7
  shared_preferences: ^2.5.5
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  speech_to_text: ^7.4.0
  flutter_tts: ^3.8.5
  fl_chart: ^0.68.0
  flutter_local_notifications: ^22.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
