/*
Description: "Update _simulateCropDoctorScan in main.dart to take imageUrl, handle preview states, and store bounding boxes."
StartLine: 5152
EndLine: 5191
TargetFile: "f:\\.Hackathon\\0.GeoFarmer\\frontend\\lib\\main.dart"
*/

// ==================== TARGET CONTENT ====================
"  Future<void> _simulateCropDoctorScan(String simulatedFilename) async {\n    setState(() {\n      _diagnoseStatus = \"Ingesting leaf crop visual layers...\";\n      _diagClass = \"\";\n    });\n\n    if (!widget.isOffline) {\n      try {\n        final response = await _makeHttpPost(\n          \"${globalBackendUrl}/detect\",\n          {\"image\": simulatedFilename, \"crop_name\": _doctorCrop.split(' ')[0]} // API processes filename directly to generate DeepSeek pathology cards\n        );\n        if (response != null) {\n          final data = json.decode(response);\n          setState(() {\n            _diagnoseStatus = \"Diagnostics Finished\";\n            _diagClass = data[\"highest_confidence_class\"];\n            _diagSeverity = data[\"severity_level\"];\n            _diagUrName = data[\"urdu_name\"];\n            _diagRemedyEn = data[\"remediation_en\"];\n            _diagRemedyUr = data[\"remediation_ur\"];\n          });\n          return;\n        }\n      } catch (e) {\n        print(\"Crop doctor API failed: $e\");\n      }\n    }\n\n    // High-fidelity fallback/offline diagnostic\n    await Future.delayed(const Duration(seconds: 1));\n    setState(() {\n      _diagnoseStatus = \"Diagnostics Finished\";\n      _diagClass = \"Rice Blast (چاول کا جھلساؤ)\";\n      _diagSeverity = \"Severe\";\n      _diagUrName = \"چاول کا جھلساؤ\";\n      _diagRemedyEn = \"1. Keep water balanced. 2. Spray Tricyclazole 75 WP immediately.\";\n      _diagRemedyUr = \"1۔ پانی کھڑا نہ ہونے دیں۔ 2۔ ٹرائی سائیکلازول 75 ڈبلیو پی کا سپرے کریں۔\";\n    });"

// ==================== REPLACEMENT CONTENT ====================
"  Future<void> _simulateCropDoctorScan(String simulatedFilename, String imageUrl) async {\n    setState(() {\n      _pickedImagePath = null;\n      _previewImageUrl = imageUrl;\n      _diagnoseStatus = \"Ingesting leaf crop visual layers...\";\n      _diagClass = \"\";\n      _boundingBoxes = [];\n    });\n\n    if (!widget.isOffline) {\n      try {\n        final response = await _makeHttpPost(\n          \"${globalBackendUrl}/detect\",\n          {\"image\": simulatedFilename, \"crop_name\": _doctorCrop.split(' ')[0]} // API processes filename directly to generate DeepSeek pathology cards\n        );\n        if (response != null) {\n          final data = json.decode(response);\n          setState(() {\n            _diagnoseStatus = \"Diagnostics Finished\";\n            _diagClass = data[\"highest_confidence_class\"];\n            _diagSeverity = data[\"severity_level\"];\n            _diagUrName = data[\"urdu_name\"];\n            _diagRemedyEn = data[\"remediation_en\"];\n            _diagRemedyUr = data[\"remediation_ur\"];\n            _boundingBoxes = data[\"bounding_boxes\"] ?? [];\n          });\n          return;\n        }\n      } catch (e) {\n        print(\"Crop doctor API failed: $e\");\n      }\n    }\n\n    // High-fidelity fallback/offline diagnostic\n    await Future.delayed(const Duration(seconds: 1));\n    final isHealthy = simulatedFilename.contains(\"healthy\");\n    setState(() {\n      _diagnoseStatus = \"Diagnostics Finished\";\n      if (isHealthy) {\n        _diagClass = \"Healthy Crop Leaf\";\n        _diagSeverity = \"None\";\n        _diagUrName = \"تندرست پتہ (Healthy Leaf)\";\n        _diagRemedyEn = \"No chemical treatment required. Maintain standard watering and fertilizer intervals.\";\n        _diagRemedyUr = \"فصل کا پتہ بالکل تندرست ہے۔ کسی بھی سپرے کی ضرورت نہیں، معمول کے مطابق پانی اور کھاد جاری رکھیں۔\";\n        _boundingBoxes = [];\n      } else {\n        _diagClass = \"Rice Blast 
<truncated 650 bytes>

