/*
Description: "Update Crop Health Scanner preview Stack widget to support network previews, bounding boxes, and clean resets."
StartLine: 2459
EndLine: 2515
TargetFile: "f:\\.Hackathon\\0.GeoFarmer\\frontend\\lib\\main.dart"
*/

// ==================== TARGET CONTENT ====================
"                    _pickedImagePath != null\n                        ? Image.file(\n                            File(_pickedImagePath!),\n                            fit: BoxFit.cover,\n                          )\n                        : buildPremiumNetworkImage(\n                            \"https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&q=80&w=600\",\n                            fit: BoxFit.cover,\n                            fallbackIcon: Icons.local_hospital,\n                          ),\n                    Container(\n                      decoration: BoxDecoration(\n                        gradient: LinearGradient(\n                          colors: [Colors.black.withOpacity(0.55), Colors.transparent, Colors.black.withOpacity(0.2)],\n                          begin: Alignment.topCenter,\n                          end: Alignment.bottomCenter,\n                        ),\n                      ),\n                    ),\n                    Positioned(\n                      top: 12,\n                      left: 12,\n                      child: Container(\n                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),\n                        decoration: BoxDecoration(\n                          color: GeoKisanTheme.primaryGreen.withOpacity(0.85),\n                          borderRadius: BorderRadius.circular(12),\n                        ),\n                        child: Text(\n                          widget.isUrdu ? \"فصل صحت اسکینر\" : \"Crop Health Scanner\",\n                          style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 10),\n                        ),\n                      ),\n                    ),\n                    if (_pickedImagePath != null)\n                      Positioned(\n                        top: 12,\n                        right: 12,\n                        child: GestureDetector(\n                          onTap: () {\n                            setS
<truncated 856 bytes>

// ==================== REPLACEMENT CONTENT ====================
"                    _pickedImagePath != null\n                        ? Image.file(\n                            File(_pickedImagePath!),\n                            fit: BoxFit.cover,\n                          )\n                        : _previewImageUrl != null\n                            ? Image.network(\n                                _previewImageUrl!,\n                                fit: BoxFit.cover,\n                                errorBuilder: (context, error, stackTrace) => buildPremiumNetworkImage(\n                                  \"https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&q=80&w=600\",\n                                  fit: BoxFit.cover,\n                                  fallbackIcon: Icons.local_hospital,\n                                ),\n                              )\n                            : buildPremiumNetworkImage(\n                                \"https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&q=80&w=600\",\n                                fit: BoxFit.cover,\n                                fallbackIcon: Icons.local_hospital,\n                              ),\n                    Container(\n                      decoration: BoxDecoration(\n                        gradient: LinearGradient(\n                          colors: [Colors.black.withOpacity(0.55), Colors.transparent, Colors.black.withOpacity(0.2)],\n                          begin: Alignment.topCenter,\n                          end: Alignment.bottomCenter,\n                        ),\n                      ),\n                    ),\n                    if (_boundingBoxes.isNotEmpty)\n                      CustomPaint(\n                        painter: YoloBoundingBoxPainter(\n                          boxes: _boundingBoxes,\n                          isUrdu: widget.isUrdu,\n                        ),\n                      ),\n                    Positioned(\n                      top: 12,\n                      left: 12,\n              
<truncated 1946 bytes>

