/*
Description: "Implement a dynamic donut chart comparing Income and Expense, savings legend, transaction delete action, and table styling in the Seasonal Financial Ledger."
StartLine: 3966
EndLine: 4057
TargetFile: "f:\\.Hackathon\\0.GeoFarmer\\frontend\\lib\\main.dart"
*/

// ==================== TARGET CONTENT ====================
"      case 'm18': // Financial Ledger Editor\n        double totalExpense = _localLedgerHistory.where((l) => l.category == \"Expense\").fold(0.0, (sum, item) => sum + item.amount);\n        double totalIncome = _localLedgerHistory.where((l) => l.category == \"Income\").fold(0.0, (sum, item) => sum + item.amount);\n        double balance = totalIncome - totalExpense;\n\n        return Column(\n          children: [\n            Row(\n              mainAxisAlignment: MainAxisAlignment.spaceBetween,\n              children: [\n                Text(\n                  widget.isUrdu ? \"موسمیاتی مالیاتی کھاتا (لیجر)\" : \"Financial Ledger Manager\",\n                  style: GeoKisanTheme.getHeaderStyle(isUrdu: widget.isUrdu, fontSize: 14, color: GeoKisanTheme.primaryGreen),\n                ),\n                Text(\n                  widget.isUrdu ? \"نیٹ بیلنس: $balance روپے\" : \"Net Balance: Rs. $balance\",\n                  style: TextStyle(color: balance >= 0 ? Colors.green : Colors.red, fontWeight: FontWeight.bold),\n                ),\n              ],\n            ),\n            const SizedBox(height: 12),\n            Card(\n              color: GeoKisanTheme.surfaceCream,\n              child: Padding(\n                padding: const EdgeInsets.all(12.0),\n                child: Column(\n                  children: [\n                    TextField(\n                      controller: _ledgerDescController,\n                      decoration: InputDecoration(\n                        labelText: widget.isUrdu ? \"خرچے یا آمدنی کی تفصیل\" : \"Transaction description\",\n                      ),\n                    ),\n                    Row(\n                      children: [\n                        Expanded(\n                          child: TextField(\n                            controller: _ledgerAmountController,\n                            decoration: const InputDecoration(labelText: \"Amount (Rs)\"),\n                            keyboardType: T
<truncated 2438 bytes>

// ==================== REPLACEMENT CONTENT ====================
"      case 'm18': // Financial Ledger Editor\n        double totalExpense = _localLedgerHistory.where((l) => l.category == \"Expense\").fold(0.0, (sum, item) => sum + item.amount);\n        double totalIncome = _localLedgerHistory.where((l) => l.category == \"Income\").fold(0.0, (sum, item) => sum + item.amount);\n        double balance = totalIncome - totalExpense;\n\n        bool hasData = totalIncome > 0 || totalExpense > 0;\n        double incomePercentage = hasData ? (totalIncome / (totalIncome + totalExpense)) * 100 : 0.0;\n        double expensePercentage = hasData ? (totalExpense / (totalIncome + totalExpense)) * 100 : 0.0;\n\n        // Inline legend builder helper\n        final legendItem = (Color color, String label, double amount) {\n          return Row(\n            crossAxisAlignment: CrossAxisAlignment.start,\n            children: [\n              Container(\n                width: 10,\n                height: 10,\n                margin: const EdgeInsets.only(top: 3, right: 6),\n                decoration: BoxDecoration(shape: BoxShape.circle, color: color),\n              ),\n              Expanded(\n                child: Column(\n                  crossAxisAlignment: CrossAxisAlignment.start,\n                  children: [\n                    Text(label, style: const TextStyle(fontSize: 10, color: Colors.grey)),\n                    Text(\n                      \"Rs. ${amount.toStringAsFixed(0)}\",\n                      style: TextStyle(\n                        fontSize: 11,\n                        fontWeight: FontWeight.bold,\n                        color: color,\n                      ),\n                    ),\n                  ],\n                ),\n              ),\n            ],\n          );\n        };\n\n        return Column(\n          children: [\n            Row(\n              mainAxisAlignment: MainAxisAlignment.spaceBetween,\n              children: [\n                Text(\n                  widget.isUrdu ? \"موسمیاتی مالیاتی کھاتا (لیجر)\" :
<truncated 9889 bytes>

