/*
Description: "Overhaul BoundaryPainter and FarmBoundaryDrawingScreen in main.dart to implement Earth Engine Satellite analysis, dynamic ray-casting grid overlay, and bilingual reports."
StartLine: 5777
EndLine: 6172
TargetFile: "f:\\.Hackathon\\0.GeoFarmer\\frontend\\lib\\main.dart"
*/

// ==================== TARGET CONTENT ====================
"// ==========================================\n// FARM BOUNDARY DRAWING SYSTEM & PAINTER\n// ==========================================\n\nclass BoundaryPainter extends CustomPainter {\n  final List<Offset> points;\n  final bool isClosed;\n  final Offset? hoverPoint;\n\n  BoundaryPainter({\n    required this.points,\n    this.isClosed = false,\n    this.hoverPoint,\n  });\n\n  @override\n  void paint(Canvas canvas, Size size) {\n    if (points.isEmpty) return;\n\n    final fillPaint = Paint()\n      ..color = const Color(0x334A7C2F) // Translucent green fill\n      ..style = PaintingStyle.fill;\n\n    final strokePaint = Paint()\n      ..color = const Color(0xFF4A7C2F)\n      ..style = PaintingStyle.stroke\n      ..strokeWidth = 3.0;\n\n    final activeStrokePaint = Paint()\n      ..color = const Color(0xFFC8860A)\n      ..style = PaintingStyle.stroke\n      ..strokeWidth = 2.0\n      ..strokeCap = StrokeCap.round;\n\n    final pointPaint = Paint()\n      ..color = const Color(0xFFC8860A)\n      ..style = PaintingStyle.fill;\n\n    final startPointPaint = Paint()\n      ..color = const Color(0xFF4A7C2F)\n      ..style = PaintingStyle.fill;\n\n    final path = Path();\n    path.moveTo(points[0].dx, points[0].dy);\n    for (int i = 1; i < points.length; i++) {\n      path.lineTo(points[i].dx, points[i].dy);\n    }\n\n    if (isClosed && points.length >= 3) {\n      path.close();\n      canvas.drawPath(path, fillPaint);\n      canvas.drawPath(path, strokePaint);\n    } else {\n      canvas.drawPath(path, strokePaint);\n      if (hoverPoint != null) {\n        canvas.drawLine(points.last, hoverPoint!, activeStrokePaint);\n      }\n    }\n\n    // Draw point markers\n    for (int i = 0; i < points.length; i++) {\n      final p = points[i];\n      if (i == 0) {\n        canvas.drawCircle(p, 8.0, startPointPaint);\n        canvas.drawCircle(p, 5.0, Paint()..color = Colors.white);\n      } else {\n        canvas.drawCircle(p, 6.0, pointPaint);\n      }\n      // Draw index text to help identify the points\n      final t
<truncated 11582 bytes>

// ==================== REPLACEMENT CONTENT ====================
"// ==========================================\n// FARM BOUNDARY DRAWING SYSTEM & PAINTER\n// ==========================================\n\nclass BoundaryPainter extends CustomPainter {\n  final List<Offset> points;\n  final bool isClosed;\n  final Offset? hoverPoint;\n  final String analysisType; // \"none\", \"ndvi\", \"thermal\"\n  final List<Map<String, dynamic>> gridOverlayPoints;\n\n  BoundaryPainter({\n    required this.points,\n    this.isClosed = false,\n    this.hoverPoint,\n    this.analysisType = \"none\",\n    this.gridOverlayPoints = const [],\n  });\n\n  @override\n  void paint(Canvas canvas, Size size) {\n    if (points.isEmpty) return;\n\n    final fillPaint = Paint()\n      ..color = analysisType == \"none\" ? const Color(0x334A7C2F) : Colors.transparent\n      ..style = PaintingStyle.fill;\n\n    final strokePaint = Paint()\n      ..color = const Color(0xFF4A7C2F)\n      ..style = PaintingStyle.stroke\n      ..strokeWidth = 3.0;\n\n    final activeStrokePaint = Paint()\n      ..color = const Color(0xFFC8860A)\n      ..style = PaintingStyle.stroke\n      ..strokeWidth = 2.0\n      ..strokeCap = StrokeCap.round;\n\n    final pointPaint = Paint()\n      ..color = const Color(0xFFC8860A)\n      ..style = PaintingStyle.fill;\n\n    final startPointPaint = Paint()\n      ..color = const Color(0xFF4A7C2F)\n      ..style = PaintingStyle.fill;\n\n    final path = Path();\n    path.moveTo(points[0].dx, points[0].dy);\n    for (int i = 1; i < points.length; i++) {\n      path.lineTo(points[i].dx, points[i].dy);\n    }\n\n    if (isClosed && points.length >= 3) {\n      path.close();\n      canvas.drawPath(path, fillPaint);\n      canvas.drawPath(path, strokePaint);\n      \n      // Draw grid overlay points for satellite raster scan\n      if (analysisType != \"none\") {\n        for (var gp in gridOverlayPoints) {\n          final Offset offset = gp[\"offset\"];\n          final int cls = gp[\"class\"];\n          \n          Color c = Colors.grey;\n          if (analysisType == \"ndvi\") {\n            
<truncated 30374 bytes>

