/*
Description: "Update _uploadCropLeafFile in main.dart to decode bounding boxes and set simulated offline boxes."
StartLine: 1491
EndLine: 1617
TargetFile: "f:\\.Hackathon\\0.GeoFarmer\\frontend\\lib\\main.dart"
*/

// ==================== TARGET CONTENT ====================
"        if (response.statusCode == 200) {\n          final data = json.decode(response.body);\n          setState(() {\n            _diagnoseStatus = \"Diagnostics Finished\";\n            _diagClass = data[\"highest_confidence_class\"];\n            _diagSeverity = data[\"severity_level\"];\n            _diagUrName = data[\"urdu_name\"] ?? \"\";\n            _diagRemedyEn = data[\"remediation_en\"];\n            _diagRemedyUr = data[\"remediation_ur\"];\n          });\n          return;\n        }\n      } catch (e) {\n        print(\"Diagnostics error: $e\");\n      }\n    }\n\n    // High-fidelity fallback/offline disease generator (Senior Dev standard)\n    await Future.delayed(const Duration(seconds: 1));\n    final lowerName = file.name.toLowerCase();\n    final lowerPath = file.path.toLowerCase();\n    final isHealthy = lowerName.contains(\"healthy\") || lowerPath.contains(\"healthy\");\n    \n    setState(() {\n      _diagnoseStatus = \"Diagnostics Finished\";\n      if (isHealthy) {\n        _diagClass = \"Healthy Crop Leaf\";\n        _diagSeverity = \"None\";\n        _diagUrName = \"تندرست پتہ (Healthy Leaf)\";\n        _diagRemedyUr = \"فصل کا پتہ بالکل تندرست ہے۔ کسی بھی سپرے کی ضرورت نہیں، معمول کے مطابق پانی اور کھاد جاری رکھیں۔\";\n        _diagRemedyEn = \"No chemical treatment required. Maintain standard watering and fertilizer intervals.\";\n      } else {\n        final crop = _doctorCrop.toLowerCase();\n        if (crop.contains(\"cotton\")) {\n          _diagClass = \"Cotton Leaf Curl Virus\";\n          _diagSeverity = \"Moderate\";\n          _diagUrName = \"کپاس کا پتا مروڑ وائرس\";\n          _diagRemedyUr = \"1۔ سفید مکھی کو کنٹرول کرنے کے لیے ایمیڈا کلوپرڈ کا سپرے کریں۔\";\n          _diagRemedyEn = \"1. Spray Imidacloprid to control Whitefly population.\";\n        } else if (crop.contains(\"rice\")) {\n          _diagClass = \"Rice
<truncated 6000 bytes>

// ==================== REPLACEMENT CONTENT ====================
"        if (response.statusCode == 200) {\n          final data = json.decode(response.body);\n          setState(() {\n            _diagnoseStatus = \"Diagnostics Finished\";\n            _diagClass = data[\"highest_confidence_class\"];\n            _diagSeverity = data[\"severity_level\"];\n            _diagUrName = data[\"urdu_name\"] ?? \"\";\n            _diagRemedyEn = data[\"remediation_en\"];\n            _diagRemedyUr = data[\"remediation_ur\"];\n            _boundingBoxes = data[\"bounding_boxes\"] ?? [];\n          });\n          return;\n        }\n      } catch (e) {\n        print(\"Diagnostics error: $e\");\n      }\n    }\n\n    // High-fidelity fallback/offline disease generator (Senior Dev standard)\n    await Future.delayed(const Duration(seconds: 1));\n    final lowerName = file.name.toLowerCase();\n    final lowerPath = file.path.toLowerCase();\n    final isHealthy = lowerName.contains(\"healthy\") || lowerPath.contains(\"healthy\");\n    \n    setState(() {\n      _diagnoseStatus = \"Diagnostics Finished\";\n      if (isHealthy) {\n        _diagClass = \"Healthy Crop Leaf\";\n        _diagSeverity = \"None\";\n        _diagUrName = \"تندرست پتہ (Healthy Leaf)\";\n        _diagRemedyUr = \"فصل کا پتہ بالکل تندرست ہے۔ کسی بھی سپرے کی ضرورت نہیں، معمول کے مطابق پانی اور کھاد جاری رکھیں۔\";\n        _diagRemedyEn = \"No chemical treatment required. Maintain standard watering and fertilizer intervals.\";\n        _boundingBoxes = [];\n      } else {\n        final crop = _doctorCrop.toLowerCase();\n        if (crop.contains(\"cotton\")) {\n          _diagClass = \"Cotton Leaf Curl Virus\";\n          _diagSeverity = \"Moderate\";\n          _diagUrName = \"کپاس کا پتا مروڑ وائرس\";\n          _diagRemedyUr = \"1۔ سفید مکھی کو کنٹرول کرنے کے لیے ایمیڈا کلوپرڈ کا سپرے کریں۔\";\n          _diagRemedyEn = \"1. Spray Imidacloprid to control Whitefly 
<truncated 6360 bytes>

